### ISSUE TITLE
https://v2.cn.vuejs.org/ 搜索功能失效，跳转地址错误

### ISSUE THREAD

**Issue by Mingscript** [vuejs/v2.cn.vuejs.org#1222]
举例：搜索跳转地址为https://cn.vuejs.org/v2/api/#destroyed，
但实际应为https://v2.cn.vuejs.org/v2/api/#destroyed

**Comment by Adashuai5** [comment]
是否是 Algolia 配置问题

**Comment by Mingscript** [comment]
> 是否是 Algolia 配置问题

我感觉也是的，我看了下，搜索跳转的逻辑应该是不在代码中。

**Comment by Jinjiang** [comment]
已修复
