### ISSUE TITLE
Vue.config.productionTip = false 无效

### ISSUE THREAD

**Issue by CandyKIng1991** [vuejs/v2.cn.vuejs.org#1227]
Vue.config.productionTip = false 无效 这个加载代码中时而好使,时而不好使,这个问题怎么解决,网上说直接改Vue.js中的代码,但是,这不是一个不稳妥的方法吗?希望给出一个官方的好办法

**Comment by CandyKIng1991** [comment]
Vue.config.devtools = false 也是无效的

**Comment by Justineo** [comment]
这里不负责解答使用问题，只讨论翻译相关的内容，谢谢。此类问题可以去 vuejs/vue 项目的 Discussions 板块讨论，或提 issue 并给出问题的最小化复现。
